<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_node_insert().
 */
function upsa_notifier_node_insert(NodeInterface $node) {
  if ($node->bundle() !== 'participant_of_the_event') {
    return;
  }

  $mail_manager = \Drupal::service('plugin.manager.mail');
  $module = 'upsa_notifier';
  $langcode = \Drupal::currentUser()->getPreferredLangcode();

  // Common event data.
  $event_data = [
    'event' => $node->get('field_event')->entity->label(),
    'email' => $node->get('field_email')->value,
    'title' => $node->get('title')->value,
    'notes' => $node->get('field_notes')->value,
    'educational_institution' => $node->get('field_educational_institution')->value,
  ];

  // Send email to admin.
  send_upsa_notification($mail_manager, $module, 'notify_admin', $event_data, \Drupal::config('system.site')->get('mail'), $langcode, );

  // Send email to participant if email is provided.
  $participant_email = $node->get('field_email')->value;
  if (!empty($participant_email)) {
    send_upsa_notification($mail_manager, $module, 'notify_admin', $event_data, $participant_email, $langcode, );
  }
}

/**
 * Helper function to send UPSA notifications.
 */
function send_upsa_notification($mail_manager, $module, $key, $event_data, $recipient_email, $langcode, bool $is_admin = FALSE) {
  $params = $event_data;
  $params['message'] = $is_admin ? 'A new participant of the "'. $params['event'] . '" has been created.'
    : 'You have been registered as a participant of the "' . $params['event'] . '".';

  $result = $mail_manager->mail($module, $key, $recipient_email, $langcode, $params, NULL, TRUE);

  if ($result['result'] !== TRUE) {
    \Drupal::logger('upsa_notifier')->error("Mail not sent to {$recipient_email}.");
  } else {
    \Drupal::logger('upsa_notifier')->info("Mail sent to {$recipient_email} for node creation.");
  }
}


/**
 * Implements hook_mail().
 */
function upsa_notifier_mail($key, &$message, $params) {
  switch ($key) {
    case 'notify_admin':
      // Set the email subject.
      $message['subject'] = t('New participant_of_the_event Node Created');

      // Render the email body using the Twig template.
      $renderable = [
        '#theme' => 'upsa_notifier_email',
        '#message' => $params['message'],
        '#event' => $params['event'],
        '#title' => $params['title'],
        '#email' => $params['email'],
        '#notes' => $params['notes'],
        '#educational_institution' => $params['educational_institution'],
      ];
      $message['body'][] = \Drupal::service('renderer')->renderRoot($renderable);

      // Set the email headers to send HTML mail.
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8';
      break;
  }
}


/**
 * Implements hook_theme().
 */
function upsa_notifier_theme($existing, $type, $theme, $path) {
  return [
    'upsa_notifier_email' => [
      'variables' => [
        'message' => NULL,
        'event' => NULL,
        'title' => NULL,
        'email' => NULL,
        'notes' => NULL,
        'educational_institution' => NULL
      ],
      'template' => 'email-template',
      'path' => $path . '/templates',
    ],
  ];
}
